### ISSUE TITLE
Virus total says its a virus, is it true or a bug? (Comunity please coment)

### ISSUE THREAD

**Issue by Yeney1273** [HecurH/Kinito#8]
You see, i downloaded it and passed it trough virus total and it told me it had trojan, Here is the evidence: [Virus total](https://www.virustotal.com/gui/file/2e9ce6c897e4e351a3f189ec7947133a1a65734c9bd8362a60d2db5f0936ebba/detection)

Can anyone tell me their experience?

**Comment by ghost** [comment]
i don't think this is a virus and even if you look at the assembly with dnspy there shouldn't be any issues

**Comment by Yeney1273** [comment]
Alright thanks!

**Comment by Yeney1273** [comment]
Help? my windows defender says its a virus (Yes its in spanish)

![image](https://github.com/HecurH/Kinito/assets/157189777/0b6e5fb7-6d92-4f34-a07d-35eb6dacde93)

**Comment by Yeney1273** [comment]
Nvm found out how to execute it!
